### ISSUE TITLE
运行main，遇错

### ISSUE THREAD

**Issue by luckypoem** [alanyang/whiteshadow#2]
hi。

root@RegalMusty-VM:~/go/gopath/src/whiteshadow/cmd/server# ./main -port 3366
2018/06/21 02:18:03 Listen sock5 server on 3366
2018/06/21 02:19:46 Client 183.x.y.57:39536 connected.
2018/06/21 02:19:46 Shadowsocks
2018/06/21 02:19:46 Shadow
2018/06/21 02:19:46 f75f7d082bcba61f9be960faf9eaa4d8
panic: runtime error: slice bounds out of range

goroutine 5 [running]:
whiteshadow/sock5.(*serverProtocol).shadowRequest(0xc42004c150, 0xc42007c000, 0x3, 0x800, 0x0, 0x0, 0x0)
	/root/go/gopath/src/whiteshadow/sock5/protocol.go:223 +0x368
whiteshadow/sock5.(*serverProtocol).(whiteshadow/sock5.shadowRequest)-fm(0xc42007c000, 0x3, 0x800, 0x800, 0x3, 0x0)
	/root/go/gopath/src/whiteshadow/sock5/protocol.go:67 +0x48
whiteshadow/sock5.(*serverProtocol).Process(0xc42004c150)
	/root/go/gopath/src/whiteshadow/sock5/protocol.go:88 +0xe8
created by main.main
	/root/go/gopath/src/whiteshadow/cmd/server/main.go:32 +0x451
root@RegalMusty-VM:~/go/gopath/src/whiteshadow/cmd/server#

怎么解决？

**Comment by luckypoem** [comment]
哦，知道原因了。像这样./main -port 3366 指定端口是不行的，必须修改下面三个文件里的1080为其他端口值，这样才能修改1080端口。

root@RegalMusty-VM:~/go/gopath/src/whiteshadow# grep -ri 1080 .
./cmd/server/main.go:	flag.IntVar(&Port, "port", 1080, "Server Listen Port")
./sock5/protocol.go:	Sock5DefaultPort = 1080
./sock5/config.go:		Port:          1080,
root@RegalMusty-VM:~/go/gopath/src/whiteshadow#
